/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Challenge */
        post: operations["request_challenge_api_v1_auth_challenges_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Session */
        get: operations["current_session_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        /** Logout */
        delete: operations["logout_api_v1_auth_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_api_v1_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/browser-companion/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_v1_browser_companion_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/browser-companion/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Device */
        delete: operations["revoke_device_api_v1_browser_companion_devices__device_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/browser-companion/extension/captures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Capture */
        post: operations["submit_capture_api_v1_browser_companion_extension_captures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/browser-companion/extension/grant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect Extension */
        delete: operations["disconnect_extension_api_v1_browser_companion_extension_grant_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/browser-companion/extension/pairings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Pairing */
        post: operations["create_pairing_api_v1_browser_companion_extension_pairings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/browser-companion/extension/pairings/{pairing_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pairing Status */
        get: operations["pairing_status_api_v1_browser_companion_extension_pairings__pairing_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/browser-companion/extension/pairings/{pairing_id}:exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange Pairing */
        post: operations["exchange_pairing_api_v1_browser_companion_extension_pairings__pairing_id__exchange_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/browser-companion/pairings/{pairing_id}:approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Pairing */
        post: operations["approve_pairing_api_v1_browser_companion_pairings__pairing_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_v1_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_api_v1_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/messages/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message Stream
         * @description Stream a browser-safe lifecycle while retaining JSON compatibility.
         *
         *     The channel service still owns identity resolution, idempotency,
         *     persistence, and answer projection.  This route only wraps that one
         *     execution in a bounded, typed SSE envelope; it never starts a second
         *     Agent task or persistence path.
         */
        post: operations["send_message_stream_api_v1_conversations__conversation_id__messages_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Conversation */
        post: operations["reset_conversation_api_v1_conversations__conversation_id__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Conversation
         * @description Permanently remove one thread owned by the current web identity.
         */
        delete: operations["delete_conversation_api_v1_conversations__thread_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{thread_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation Turns */
        get: operations["get_conversation_turns_api_v1_conversations__thread_id__turns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest-dispatches/{dispatch_public_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dispatch */
        get: operations["dispatch_api_v1_ingest_dispatches__dispatch_public_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_v1_library_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/items/{item_public_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_v1_library_items__item_public_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_api_v1_library_items__item_public_id__patch"];
        trace?: never;
    };
    "/api/v1/library/items/{item_public_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transcript Page */
        get: operations["transcript_page_api_v1_library_items__item_public_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/items/{item_public_id}:archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive */
        post: operations["archive_api_v1_library_items__item_public_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/items/{item_public_id}:restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore */
        post: operations["restore_api_v1_library_items__item_public_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/items/{item_public_id}:retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_v1_library_items__item_public_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/items:batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Batch */
        post: operations["save_batch_api_v1_library_items_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/link-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Token */
        post: operations["create_token_api_v1_link_tokens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/link-tokens/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consume Token */
        post: operations["consume_token_api_v1_link_tokens_consume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptedResponse */
        AcceptedResponse: {
            /**
             * Status
             * @default accepted
             * @constant
             */
            status: "accepted";
        };
        /** AuthErrorResponse */
        AuthErrorResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** BatchItemResponse */
        BatchItemResponse: {
            /** Input Index */
            input_index: number;
            /** Item Public Id */
            item_public_id?: string | null;
            /** Lifecycle */
            lifecycle?: ("archived" | "ready" | "needs_action" | "failed" | "processing" | "queued") | null;
            /** Result Id */
            result_id: string;
            /** Safe Error Code */
            safe_error_code?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "already_exists" | "unsupported_url" | "invalid_url" | "queue_unavailable" | "create_failed" | "quota_exceeded";
        };
        /** BatchSaveRequest */
        BatchSaveRequest: {
            /** Urls */
            urls: string[];
            /** Why Saved */
            why_saved?: string | null;
        };
        /** BatchSaveResponse */
        BatchSaveResponse: {
            /** Results */
            results: components["schemas"]["BatchItemResponse"][];
        };
        /** BrowserCaptureRequest */
        BrowserCaptureRequest: {
            /** Canonical Url */
            canonical_url: string;
            caption: components["schemas"]["CaptureCaption"];
            /** Client Version */
            client_version: string;
            /** Content Hash */
            content_hash: string;
            metadata: components["schemas"]["CaptureMetadata"];
            /** Page Url */
            page_url?: string | null;
            /**
             * Platform
             * @enum {string}
             */
            platform: "youtube" | "ntu_kaltura";
            /** Platform Id */
            platform_id: string;
            /**
             * Protocol Version
             * @constant
             */
            protocol_version: "capture.v1";
        };
        /** BrowserCaptureResponse */
        BrowserCaptureResponse: {
            /** Capture Id */
            capture_id: string | null;
            /** Item Public Id */
            item_public_id: string;
            /** Lifecycle */
            lifecycle: string;
            /** Platform */
            platform: string;
            /** Safe Error Code */
            safe_error_code?: string | null;
            /** Status */
            status: string;
        };
        /** BrowserDeviceListResponse */
        BrowserDeviceListResponse: {
            /** Devices */
            devices: components["schemas"]["BrowserDeviceResponse"][];
        };
        /** BrowserDeviceResponse */
        BrowserDeviceResponse: {
            /** Client Label */
            client_label: string;
            /** Client Version */
            client_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Device Id */
            device_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /**
             * Archive
             * @default true
             */
            archive: boolean;
            /**
             * Browser Companion
             * @default true
             */
            browser_companion: boolean;
            /**
             * Chat
             * @default true
             */
            chat: boolean;
            /**
             * Max Save Batch Size
             * @default 10
             */
            max_save_batch_size: number;
            /**
             * Save Enabled
             * @default true
             */
            save_enabled: boolean;
            /**
             * Summary Generation
             * @default false
             */
            summary_generation: boolean;
            /**
             * Supported Platforms
             * @default [
             *       "youtube",
             *       "bilibili",
             *       "ntu_kaltura"
             *     ]
             */
            supported_platforms: ("youtube" | "bilibili" | "ntu_kaltura")[];
            /**
             * Transcript Pagination
             * @default true
             */
            transcript_pagination: boolean;
            /**
             * Web Login Channels
             * @default [
             *       "telegram",
             *       "wechat"
             *     ]
             */
            web_login_channels: ("email" | "telegram" | "wechat")[];
        };
        /** CaptureCaption */
        CaptureCaption: {
            /** Cues */
            cues?: components["schemas"]["CaptureCue"][];
            /** Language */
            language?: string | null;
            /** Source */
            source?: ("official_cc" | "auto_caption") | null;
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "unavailable";
        };
        /** CaptureChapter */
        CaptureChapter: {
            /** End Sec */
            end_sec?: number | null;
            /** Start Sec */
            start_sec: number;
            /** Title */
            title: string;
        };
        /** CaptureCue */
        CaptureCue: {
            /** End Sec */
            end_sec: number;
            /** Start Sec */
            start_sec: number;
            /** Text */
            text: string;
        };
        /** CaptureMetadata */
        CaptureMetadata: {
            /** Author */
            author?: string | null;
            /** Chapters */
            chapters?: components["schemas"]["CaptureChapter"][];
            /** Cover Url */
            cover_url?: string | null;
            /** Description */
            description?: string | null;
            /** Duration Sec */
            duration_sec?: number | null;
            /** Language */
            language?: string | null;
            /** Published At */
            published_at?: string | null;
            /** Tags */
            tags?: string[];
            /** Title */
            title?: string | null;
        };
        /** ChallengeCreateRequest */
        ChallengeCreateRequest: {
            /**
             * Target Channel
             * @enum {string}
             */
            target_channel: "telegram" | "wechat";
        };
        /** ChallengeCreateResponse */
        ChallengeCreateResponse: {
            /** Browser Secret */
            browser_secret: string;
            /** Command */
            command: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Public Id */
            public_id: string;
            /**
             * Target Channel
             * @enum {string}
             */
            target_channel: "telegram" | "wechat";
        };
        /** ChallengeStatusResponse */
        ChallengeStatusResponse: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "approved";
        };
        /**
         * ChapterResponse
         * @description Normalized public subset of connector-provided chapter metadata.
         */
        ChapterResponse: {
            /** End */
            end?: number | null;
            /** End Sec */
            end_sec?: number | null;
            /** End Time */
            end_time?: number | null;
            /** Start */
            start?: number | null;
            /** Start Sec */
            start_sec?: number | null;
            /** Start Time */
            start_time?: number | null;
            /** Title */
            title?: string | null;
        };
        /** ConsumeLinkTokenInput */
        ConsumeLinkTokenInput: {
            /** Token */
            token: string;
        };
        /**
         * ConversationCitationResponse
         * @description Browser-safe citation projection without internal row identifiers.
         */
        ConversationCitationResponse: {
            /** Excerpt */
            excerpt: string;
            /**
             * Start Sec
             * @default null
             */
            start_sec: number | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /**
         * ConversationHistoryItemResponse
         * @description A compact browser-safe projection for the conversation sidebar.
         */
        ConversationHistoryItemResponse: {
            /** Conversation Id */
            conversation_id: string;
            /** Preview */
            preview: string;
            /** Thread Id */
            thread_id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ConversationHistoryPageResponse
         * @description A bounded, opaque-cursor page of the current identity's threads.
         */
        ConversationHistoryPageResponse: {
            /** Items */
            items?: components["schemas"]["ConversationHistoryItemResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * ConversationPlanItem
         * @description Browser-safe projection of one transient turn plan item.
         */
        ConversationPlanItem: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "in_progress" | "completed" | "blocked";
            /** Title */
            title: string;
        };
        /**
         * ConversationResponse
         * @description Stable compatibility response for the retained conversation surface.
         */
        ConversationResponse: {
            /** Action Results */
            action_results?: {
                [key: string]: unknown;
            }[];
            /** Citations */
            citations?: components["schemas"]["ConversationCitationResponse"][];
            /**
             * Error Code
             * @default null
             */
            error_code: string | null;
            /** Status */
            status: string;
            /** Text */
            text: string;
            /**
             * Thread Id
             * @default null
             */
            thread_id: string | null;
        };
        /**
         * ConversationStreamEvent
         * @description The small, public event envelope used by the browser SSE client.
         *
         *     The event type and activity values are intentionally closed sets.  Agent
         *     provider chunks, tool arguments, diagnostics, and hidden reasoning never
         *     cross this boundary.
         */
        ConversationStreamEvent: {
            /** Activity */
            activity?: ("preparing" | "retrieving" | "planning_answer" | "composing" | "completed" | "failed" | "cancelled") | null;
            /** Citation Ids */
            citation_ids?: number[];
            /** Citations */
            citations?: components["schemas"]["ConversationCitationResponse"][];
            /** Error Code */
            error_code?: string | null;
            /** Message */
            message?: string | null;
            /** Message Id */
            message_id: string;
            /** Plan */
            plan?: components["schemas"]["ConversationPlanItem"][] | null;
            /** Reason */
            reason?: ("provider_failure" | "timeout" | "cancelled") | null;
            /** Request Id */
            request_id: string;
            response?: components["schemas"]["ConversationResponse"] | null;
            /** Result Count */
            result_count?: number | null;
            /** Section Id */
            section_id?: string | null;
            /** Sequence */
            sequence: number;
            /** Status */
            status?: ("grounded" | "unsupported") | null;
            /** Step Code */
            step_code?: ("updating_plan" | "searching_library" | "reading_context" | "checking_source" | "reviewing_library" | "checking_item" | "handling_save" | "managing_library" | "working") | null;
            /** Step Id */
            step_id?: string | null;
            /** Step Outcome */
            step_outcome?: ("completed" | "failed" | "skipped") | null;
            /** Text */
            text?: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "started" | "activity" | "step_started" | "step_completed" | "plan_updated" | "section_started" | "text_delta" | "section_completed" | "section_aborted" | "completed" | "error" | "cancelled";
        };
        /**
         * ConversationTurnResponse
         * @description One persisted public conversation turn without model/provider data.
         */
        ConversationTurnResponse: {
            /** Action Results */
            action_results?: {
                [key: string]: unknown;
            }[];
            /** Assistant Text */
            assistant_text: string;
            /** Citations */
            citations?: components["schemas"]["ConversationCitationResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code?: string | null;
            /** Status */
            status: string;
            /** User Text */
            user_text: string;
        };
        /**
         * ConversationTurnsResponse
         * @description The saved transcript for one thread owned by the current identity.
         */
        ConversationTurnsResponse: {
            /** Conversation Id */
            conversation_id: string;
            /** Thread Id */
            thread_id: string;
            /** Turns */
            turns?: components["schemas"]["ConversationTurnResponse"][];
        };
        /** DispatchResponse */
        DispatchResponse: {
            /** Attempt */
            attempt: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Item Public Id */
            item_public_id: string;
            /** Public Id */
            public_id: string;
            /** State */
            state: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EmailChallengeRequest
         * @description Request an email verification code.
         *
         *     Server-side normalization and validation remain authoritative; the
         *     bounded field prevents oversized bodies from reaching the auth service.
         */
        EmailChallengeRequest: {
            /** Email */
            email: string;
        };
        /** EmailVerifyRequest */
        EmailVerifyRequest: {
            /** Code */
            code: string;
            /** Email */
            email: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** LibraryItemResponse */
        LibraryItemResponse: {
            /** Author */
            author: string | null;
            /** Available Actions */
            available_actions: string[];
            /** Chapters */
            chapters: components["schemas"]["ChapterResponse"][];
            /** Cover Url */
            cover_url: string | null;
            /** Description */
            description: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            /** Error Code */
            error_code: string | null;
            /** Kind */
            kind: string;
            /** Lang */
            lang: string | null;
            /** Latest Dispatch Public Id */
            latest_dispatch_public_id: string | null;
            /**
             * Lifecycle
             * @enum {string}
             */
            lifecycle: "archived" | "ready" | "needs_action" | "failed" | "processing" | "queued";
            /** Platform */
            platform: string;
            /** Public Id */
            public_id: string;
            /** Published At */
            published_at: string | null;
            /**
             * Saved At
             * Format: date-time
             */
            saved_at: string;
            /** Summary */
            summary?: string | null;
            /** Tags */
            tags: string[];
            /** Text Source */
            text_source: string;
            /** Title */
            title: string | null;
            /** Url */
            url: string;
            /** Why Saved */
            why_saved: string | null;
        };
        /** LibraryPageResponse */
        LibraryPageResponse: {
            /** Is True First Empty */
            is_true_first_empty: boolean;
            /** Items */
            items: components["schemas"]["LibraryItemResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** LinkTokenInput */
        LinkTokenInput: {
            /** Target Channel */
            target_channel: string;
        };
        /** LinkTokenResponse */
        LinkTokenResponse: {
            /** Token */
            token: string;
        };
        /** LinkedResponse */
        LinkedResponse: {
            /**
             * Linked
             * @default true
             */
            linked: boolean;
        };
        /** MessageInput */
        MessageInput: {
            /** Message Id */
            message_id: string;
            /** Text */
            text: string;
        };
        /** PairingApprovalResponse */
        PairingApprovalResponse: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Pairing Id */
            pairing_id: string;
            /**
             * Status
             * @default approved
             * @constant
             */
            status: "approved";
        };
        /** PairingCreateRequest */
        PairingCreateRequest: {
            /** Challenge */
            challenge: string;
            /** Client Label */
            client_label: string;
            /** Client Version */
            client_version: string;
        };
        /** PairingCreateResponse */
        PairingCreateResponse: {
            /** Approval Url */
            approval_url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Pairing Id */
            pairing_id: string;
        };
        /** PairingExchangeRequest */
        PairingExchangeRequest: {
            /** Verifier */
            verifier: string;
        };
        /** PairingExchangeResponse */
        PairingExchangeResponse: {
            /** Access Token */
            access_token: string;
            /** Device Id */
            device_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Token Type
             * @default Bearer
             * @constant
             */
            token_type: "Bearer";
        };
        /** PairingStatusResponse */
        PairingStatusResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "approved" | "expired" | "used";
        };
        /** SessionResponse */
        SessionResponse: {
            /**
             * Authenticated
             * @default true
             * @constant
             */
            authenticated: true;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Login Channel
             * @enum {string}
             */
            login_channel: "email" | "telegram" | "wechat";
        };
        /** TranscriptBlockResponse */
        TranscriptBlockResponse: {
            /** End Sec */
            end_sec: number;
            /** Ordinal */
            ordinal: number;
            /** Source Url */
            source_url: string;
            /** Start Sec */
            start_sec: number;
            /** Text */
            text: string;
        };
        /** TranscriptPageResponse */
        TranscriptPageResponse: {
            /** Blocks */
            blocks: components["schemas"]["TranscriptBlockResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WhySavedRequest */
        WhySavedRequest: {
            /** Why Saved */
            why_saved?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    request_challenge_api_v1_auth_challenges_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailChallengeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
        };
    };
    current_session_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_session_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
        };
    };
    verify_api_v1_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
        };
    };
    list_devices_api_v1_browser_companion_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowserDeviceListResponse"];
                };
            };
        };
    };
    revoke_device_api_v1_browser_companion_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_capture_api_v1_browser_companion_extension_captures_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrowserCaptureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowserCaptureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_extension_api_v1_browser_companion_extension_grant_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_pairing_api_v1_browser_companion_extension_pairings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairingCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pairing_status_api_v1_browser_companion_extension_pairings__pairing_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pairing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exchange_pairing_api_v1_browser_companion_extension_pairings__pairing_id__exchange_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pairing_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairingExchangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingExchangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_pairing_api_v1_browser_companion_pairings__pairing_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pairing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    list_conversations_api_v1_conversations_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationHistoryPageResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    send_message_api_v1_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    send_message_stream_api_v1_conversations__conversation_id__messages_stream_post: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageInput"];
            };
        };
        responses: {
            /** @description Server-sent public conversation events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reset_conversation_api_v1_conversations__conversation_id__reset_post: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_conversation_api_v1_conversations__thread_id__delete: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_conversation_turns_api_v1_conversations__thread_id__turns_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationTurnsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    dispatch_api_v1_ingest_dispatches__dispatch_public_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dispatch_public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_items_api_v1_library_items_get: {
        parameters: {
            query?: {
                search?: string | null;
                collection?: string | null;
                lifecycle?: ("archived" | "ready" | "needs_action" | "failed" | "processing" | "queued") | null;
                include_archived?: boolean;
                sort?: "saved_desc" | "saved_asc" | "title_asc";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryPageResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    detail_api_v1_library_items__item_public_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItemResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_api_v1_library_items__item_public_id__patch: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                item_public_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhySavedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItemResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    transcript_page_api_v1_library_items__item_public_id__transcript_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                item_public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptPageResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    archive_api_v1_library_items__item_public_id__archive_post: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                item_public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItemResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    restore_api_v1_library_items__item_public_id__restore_post: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                item_public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItemResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    retry_api_v1_library_items__item_public_id__retry_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token": string;
            };
            path: {
                item_public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItemResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    save_batch_api_v1_library_items_batch_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchSaveResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_token_api_v1_link_tokens_post: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkTokenInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkTokenResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    consume_token_api_v1_link_tokens_consume_post: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsumeLinkTokenInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkedResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
