"""SQLAlchemy models for the personal knowledge base.

Mirrors the DDL in `.trellis/tasks/08-04-video-text-kb/design.md` (数据模型
section) exactly: enum types, `content_item` + `segment` tables, the
`loc_ck` mutual-exclusion constraint, uniqueness constraints, and the
HNSW / GIN / trigram indexes on `segment`.

`app_user` is the internal tenant root. Channel identities and conversation
threads are application-owned authorization state and never model arguments.
"""

from __future__ import annotations

from datetime import datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    ARRAY,
    BigInteger,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR
from sqlalchemy.dialects.postgresql import ENUM as PgEnum
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, synonym


class Base(DeclarativeBase):
    pass


# --- Enum types (native Postgres ENUM, matches design.md DDL names) ---

platform_enum = PgEnum(
    "youtube", "bilibili", "wechat_mp", "ntu_kaltura",
    name="platform",
)

item_kind_enum = PgEnum(
    "video", "article",
    name="item_kind",
)

text_source_enum = PgEnum(
    "official_cc", "auto_caption", "asr_whisper", "article_text", "none",
    name="text_source",
)

ingest_state_enum = PgEnum(
    "pending", "fetching", "needs_extension", "needs_asr",
    "chunking", "embedding", "ready", "failed", "no_text",
    name="ingest_state",
)


class AppUser(Base):
    """Internal tenant; external platform identifiers live separately."""

    __tablename__ = "app_user"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    disabled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class ChannelIdentity(Base):
    """A trusted platform identity bound to one internal tenant."""

    __tablename__ = "channel_identity"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    app_user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("app_user.id", ondelete="CASCADE"), nullable=False
    )
    channel: Mapped[str] = mapped_column(Text, nullable=False)
    account_id: Mapped[str] = mapped_column(Text, nullable=False)
    external_user_id: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    disabled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        UniqueConstraint(
            "channel",
            "account_id",
            "external_user_id",
            name="uq_channel_identity_external",
        ),
        Index("ix_channel_identity_user", "app_user_id"),
    )


class McpAccessGrant(Base):
    """A revocable, hash-only bearer capability for the MCP adapter.

    ``grant_id`` is the stable public principal used as the MCP channel
    identity's external id.  It is deliberately unrelated to ``token_hash``
    and is safe to include in correlation metadata.  The raw bearer token is
    generated by :mod:`app.mcp_grants`, returned once, and never persisted.
    """

    __tablename__ = "mcp_access_grant"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    grant_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    # ``principal_id`` is a semantic alias used by transport code and audit
    # tooling; the persisted canonical column remains ``grant_id``.
    principal_id = synonym("grant_id")
    app_user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("app_user.id", ondelete="CASCADE"), nullable=False
    )
    token_hash: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    scope: Mapped[str] = mapped_column(Text, nullable=False, server_default="read")
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    disabled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    rotated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    last_used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    label: Mapped[str | None] = mapped_column(Text)
    created_by: Mapped[str | None] = mapped_column(Text)

    __table_args__ = (
        CheckConstraint("scope IN ('read', 'full')", name="ck_mcp_access_grant_scope"),
        CheckConstraint(
            "label IS NULL OR length(label) <= 200",
            name="ck_mcp_access_grant_label_length",
        ),
        CheckConstraint(
            "created_by IS NULL OR length(created_by) <= 128",
            name="ck_mcp_access_grant_created_by_length",
        ),
        Index("ix_mcp_access_grant_user", "app_user_id"),
        Index("ix_mcp_access_grant_active", "grant_id", "revoked_at", "disabled_at"),
    )


# A descriptive alias is useful to callers that use the initialism as a
# class name while retaining one SQLAlchemy table/model definition.
MCPAccessGrant = McpAccessGrant
McpGrant = McpAccessGrant
MCPGrant = McpAccessGrant


class ChannelLinkToken(Base):
    """Hashed, short-lived, single-use token for cross-channel linking."""

    __tablename__ = "channel_link_token"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    token_hash: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    app_user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("app_user.id", ondelete="CASCADE"), nullable=False
    )
    target_channel: Mapped[str | None] = mapped_column(Text)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    consumed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (Index("ix_channel_link_token_user", "app_user_id"),)


class WebLoginChallenge(Base):
    """Short-lived channel-assisted login approval without plaintext secrets."""

    __tablename__ = "web_login_challenge"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    public_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    code_hash: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    browser_token_hash: Mapped[str] = mapped_column(Text, nullable=False)
    requester_hash: Mapped[str] = mapped_column(Text, nullable=False)
    target_channel: Mapped[str] = mapped_column(Text, nullable=False)
    approved_app_user_id: Mapped[int | None] = mapped_column(
        BigInteger,
        ForeignKey("app_user.id", ondelete="CASCADE"),
    )
    approved_by_identity_id: Mapped[int | None] = mapped_column(
        BigInteger,
        ForeignKey("channel_identity.id", ondelete="SET NULL"),
    )
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    approved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    consumed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    cancelled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    attempt_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        Index("ix_web_login_challenge_expires_at", "expires_at"),
        Index("ix_web_login_challenge_created_at", "created_at"),
        Index(
            "ix_web_login_challenge_requester_created",
            "requester_hash",
            created_at.desc(),
        ),
        Index(
            "ix_web_login_challenge_approved_user",
            "approved_app_user_id",
            postgresql_where=text("approved_app_user_id IS NOT NULL"),
        ),
    )


class WebAuthChallenge(Base):
    """One-time, HMAC-protected email login challenge."""

    __tablename__ = "web_auth_challenge"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    email: Mapped[str] = mapped_column(Text, nullable=False)
    code_hash: Mapped[str] = mapped_column(Text, nullable=False)
    attempt_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    consumed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    invalidated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    delivery_failed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        Index("ix_web_auth_challenge_email_expiry", "email", "expires_at"),
    )


class WebSession(Base):
    """One browser session schema shared by channel and email login flows."""

    __tablename__ = "web_session"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    public_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    token_hash: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    csrf_token_hash: Mapped[str] = mapped_column(Text, nullable=False)
    app_user_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("app_user.id", ondelete="CASCADE"),
        nullable=False,
    )
    login_channel: Mapped[str] = mapped_column(Text, nullable=False)
    # Channel-assisted sessions predate this linkage.  Email-auth sessions
    # populate it; existing upstream sessions intentionally leave it NULL.
    channel_identity_id: Mapped[int | None] = mapped_column(
        BigInteger,
        ForeignKey("channel_identity.id", ondelete="CASCADE"),
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    last_used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        Index("ix_web_session_user_expires", "app_user_id", "expires_at"),
        Index("ix_web_session_expires_at", "expires_at"),
        Index(
            "ix_web_session_revoked_at",
            "revoked_at",
            postgresql_where=text("revoked_at IS NOT NULL"),
        ),
        Index("ix_web_session_token_active", "token_hash", "revoked_at"),
        Index("ix_web_session_user_active", "app_user_id", "revoked_at"),
    )


class BrowserCompanionPairing(Base):
    """Short-lived, single-use approval for one extension-held verifier."""

    __tablename__ = "browser_companion_pairing"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    public_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    challenge_hash: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    app_user_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("app_user.id", ondelete="CASCADE")
    )
    client_label: Mapped[str] = mapped_column(Text, nullable=False)
    client_version: Mapped[str] = mapped_column(Text, nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    approved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    consumed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        CheckConstraint(
            "length(client_label) BETWEEN 1 AND 200",
            name="ck_browser_companion_pairing_label",
        ),
        CheckConstraint(
            "length(client_version) BETWEEN 1 AND 64",
            name="ck_browser_companion_pairing_version",
        ),
        Index("ix_browser_companion_pairing_expires", "expires_at"),
        Index("ix_browser_companion_pairing_user", "app_user_id"),
    )


class BrowserCompanionGrant(Base):
    """Hash-only, tenant-bound capability used solely for browser captures."""

    __tablename__ = "browser_companion_grant"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    device_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    app_user_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("app_user.id", ondelete="CASCADE"),
        nullable=False,
    )
    token_hash: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    scope: Mapped[str] = mapped_column(
        Text, nullable=False, server_default="capture:write"
    )
    client_label: Mapped[str] = mapped_column(Text, nullable=False)
    client_version: Mapped[str] = mapped_column(Text, nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    disabled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    last_used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        CheckConstraint(
            "scope = 'capture:write'", name="ck_browser_companion_grant_scope"
        ),
        CheckConstraint(
            "length(client_label) BETWEEN 1 AND 200",
            name="ck_browser_companion_grant_label",
        ),
        CheckConstraint(
            "length(client_version) BETWEEN 1 AND 64",
            name="ck_browser_companion_grant_version",
        ),
        Index("ix_browser_companion_grant_user", "app_user_id"),
        Index(
            "ix_browser_companion_grant_active",
            "token_hash",
            "revoked_at",
            "disabled_at",
        ),
    )


class ConversationThread(Base):
    """One recoverable logical conversation inside a trusted channel chat."""

    __tablename__ = "conversation_thread"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    public_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    app_user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("app_user.id", ondelete="CASCADE"), nullable=False
    )
    channel_identity_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("channel_identity.id", ondelete="CASCADE"),
        nullable=False,
    )
    channel: Mapped[str] = mapped_column(Text, nullable=False)
    account_id: Mapped[str] = mapped_column(Text, nullable=False)
    external_conversation_id: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        Index("ix_conversation_thread_user_updated", "app_user_id", updated_at.desc()),
        Index(
            "uq_conversation_thread_active",
            "channel_identity_id",
            "external_conversation_id",
            unique=True,
            postgresql_where=text("closed_at IS NULL"),
        ),
    )


class ConversationTurn(Base):
    """A completed, idempotent user/assistant turn and its model history."""

    __tablename__ = "conversation_turn"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    thread_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("conversation_thread.id", ondelete="CASCADE"),
        nullable=False,
    )
    message_id: Mapped[str] = mapped_column(Text, nullable=False)
    user_text: Mapped[str] = mapped_column(Text, nullable=False)
    assistant_text: Mapped[str] = mapped_column(Text, nullable=False)
    sources: Mapped[list | dict] = mapped_column(JSONB, nullable=False)
    model_messages: Mapped[list | dict] = mapped_column(JSONB, nullable=False)
    answer_status: Mapped[str] = mapped_column(
        Text, nullable=False, server_default="legacy"
    )
    error_code: Mapped[str | None] = mapped_column(Text)
    action_results: Mapped[list | dict] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="completed")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        UniqueConstraint("thread_id", "message_id", name="uq_conversation_turn_message"),
        Index("ix_conversation_turn_thread_created", "thread_id", created_at.desc()),
    )


class PendingChannelAction(Base):
    """Versioned, expiring action state bound to one trusted conversation."""

    __tablename__ = "pending_channel_action"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    thread_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("conversation_thread.id", ondelete="CASCADE"),
        nullable=False,
    )
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    payload: Mapped[list | dict] = mapped_column(JSONB, nullable=False)
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    consumed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    consumed_message_id: Mapped[str | None] = mapped_column(Text)
    cancelled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        Index(
            "uq_pending_channel_action_thread_active",
            "thread_id",
            unique=True,
            postgresql_where=text(
                "consumed_at IS NULL AND cancelled_at IS NULL"
            ),
        ),
    )


class ContentItem(Base):
    __tablename__ = "content_item"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    public_id: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        unique=True,
        server_default=text("replace(gen_random_uuid()::text, '-', '')"),
    )
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("app_user.id"), nullable=False
    )
    platform: Mapped[str] = mapped_column(platform_enum, nullable=False)
    platform_id: Mapped[str] = mapped_column(Text, nullable=False)  # video_id / bvid / sn
    kind: Mapped[str] = mapped_column(item_kind_enum, nullable=False)
    url: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str | None] = mapped_column(Text)
    author: Mapped[str | None] = mapped_column(Text)
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    duration_sec: Mapped[int | None] = mapped_column(Integer)  # video only
    char_count: Mapped[int | None] = mapped_column(Integer)  # article only
    lang: Mapped[str | None] = mapped_column(Text)  # 'en' / 'zh' -> 驱动切分阈值
    description: Mapped[str | None] = mapped_column(Text)
    tags: Mapped[list[str] | None] = mapped_column(ARRAY(Text))
    chapters: Mapped[dict | list | None] = mapped_column(JSONB)  # YouTube: [{start,end,title}]
    cover_url: Mapped[str | None] = mapped_column(Text)

    # 用户侧
    saved_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    archived_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    why_saved: Mapped[str | None] = mapped_column(Text)
    watch_state: Mapped[str | None] = mapped_column(Text, server_default="unwatched")
    watch_pos_sec: Mapped[int | None] = mapped_column(Integer)

    # 去重与溯源
    content_hash: Mapped[str | None] = mapped_column(Text)  # 正文/转录规范化后 sha256
    raw_object_key: Mapped[str | None] = mapped_column(Text)  # MinIO: 原始 json3 / HTML
    raw_format: Mapped[str] = mapped_column(
        Text, nullable=False, server_default="json3"
    )
    text_source: Mapped[str] = mapped_column(
        text_source_enum, nullable=False, server_default="none"
    )
    state: Mapped[str] = mapped_column(
        ingest_state_enum, nullable=False, server_default="pending"
    )
    fail_reason: Mapped[str | None] = mapped_column(Text)

    # Recycle-bin lifecycle.  These fields deliberately remain separate from
    # ``state``: ingestion state is owned by the worker, while deletion and
    # purge state is owned by the management/maintenance services.
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    purge_claimed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    purge_attempts: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    purge_error_code: Mapped[str | None] = mapped_column(Text)
    # A short-lived delete-effect fence.  Restore/re-save replaces this value
    # so a late effect from an older confirmation cannot soft-delete the item
    # again after it has become visible.
    delete_claim_token: Mapped[str | None] = mapped_column(Text)

    __table_args__ = (
        UniqueConstraint(
            "user_id", "platform", "platform_id",
            name="uq_content_item_user_platform_platform_id",
        ),
        Index(
            "ix_content_item_user_saved_at",
            "user_id",
            saved_at.desc(),
            id.desc(),
            postgresql_where=text("deleted_at IS NULL"),
        ),
        Index(
            "ix_content_item_user_deleted_at",
            "user_id",
            deleted_at.desc(),
            id.desc(),
            postgresql_where=text("deleted_at IS NOT NULL"),
        ),
        Index(
            "ix_content_item_deleted_at_id",
            "deleted_at",
            id,
            postgresql_where=text("deleted_at IS NOT NULL"),
        ),
        Index("ix_content_item_saved_at", saved_at.desc()),
        Index(
            "ix_content_item_user_archived_saved_at",
            "user_id",
            "archived_at",
            saved_at.desc(),
        ),
        Index(
            "ix_content_item_content_hash",
            "content_hash",
            postgresql_where=content_hash.isnot(None),
        ),
    )


class IngestDispatch(Base):
    """Durable, idempotent claim for one asynchronous item ingestion."""

    __tablename__ = "ingest_dispatch"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    public_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    item_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("content_item.id", ondelete="CASCADE"),
        nullable=False,
    )
    # Immutable source conversation captured by the admission transaction.
    # ``NULL`` is intentional for MCP/CLI and unsupported channels; the
    # notification poller must never infer a target from a later identity.
    source_thread_id: Mapped[int | None] = mapped_column(
        BigInteger,
        ForeignKey("conversation_thread.id", ondelete="SET NULL"),
    )
    request_key: Mapped[str] = mapped_column(Text, nullable=False)
    attempt: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="1"
    )
    state: Mapped[str] = mapped_column(
        Text, nullable=False, server_default="pending"
    )
    task_id: Mapped[str | None] = mapped_column(Text)
    error_code: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        UniqueConstraint(
            "request_key",
            "item_id",
            name="uq_ingest_dispatch_request_item",
        ),
        Index(
            "uq_ingest_dispatch_item_active",
            "item_id",
            unique=True,
            postgresql_where=text(
                "state IN ('pending', 'enqueued', 'running')"
            ),
        ),
        Index(
            "ix_ingest_dispatch_created_item",
            created_at.desc(),
            "item_id",
        ),
        Index("ix_ingest_dispatch_source_thread", "source_thread_id"),
    )


class BrowserCapture(Base):
    """Durable hand-off from one authenticated extension capture to ingestion."""

    __tablename__ = "browser_capture"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    public_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    app_user_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("app_user.id", ondelete="CASCADE"),
        nullable=False,
    )
    item_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("content_item.id", ondelete="CASCADE"),
        nullable=False,
    )
    dispatch_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("ingest_dispatch.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    )
    request_key: Mapped[str] = mapped_column(Text, nullable=False)
    body_hash: Mapped[str] = mapped_column(Text, nullable=False)
    protocol_version: Mapped[str] = mapped_column(Text, nullable=False)
    client_version: Mapped[str] = mapped_column(Text, nullable=False)
    caption_status: Mapped[str] = mapped_column(Text, nullable=False)
    caption_source: Mapped[str | None] = mapped_column(Text)
    language: Mapped[str | None] = mapped_column(Text)
    capture_metadata: Mapped[dict | list] = mapped_column(
        "metadata", JSONB, nullable=False
    )
    raw_object_key: Mapped[str | None] = mapped_column(Text)
    content_hash: Mapped[str | None] = mapped_column(Text)
    state: Mapped[str] = mapped_column(Text, nullable=False, server_default="staging")
    error_code: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        UniqueConstraint(
            "app_user_id",
            "request_key",
            name="uq_browser_capture_user_request",
        ),
        CheckConstraint(
            "caption_status IN ('available', 'unavailable')",
            name="ck_browser_capture_caption_status",
        ),
        CheckConstraint(
            "state IN ('staging', 'ready', 'failed')",
            name="ck_browser_capture_state",
        ),
        CheckConstraint(
            "(caption_status = 'available' AND caption_source IN "
            "('official_cc', 'auto_caption') AND language IS NOT NULL) OR "
            "(caption_status = 'unavailable' AND caption_source IS NULL "
            "AND language IS NULL)",
            name="ck_browser_capture_caption_contract",
        ),
        Index("ix_browser_capture_item_created", "item_id", created_at.desc()),
        Index("ix_browser_capture_state", "state", "created_at"),
    )


class IngestCompletionEvent(Base):
    """Durable outbox row for one terminal ingestion dispatch attempt.

    The broker envelope intentionally contains only ``id``.  Consumers load
    the event and its tenant-owned item from the trusted database and use the
    stable row/public identifiers as their own idempotency key.
    """

    __tablename__ = "ingest_completion_event"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    public_id: Mapped[str] = mapped_column(Text, nullable=False)
    dispatch_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("ingest_dispatch.id", ondelete="CASCADE"),
        nullable=False,
    )
    item_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("content_item.id", ondelete="CASCADE"),
        nullable=False,
    )
    outcome: Mapped[str] = mapped_column(Text, nullable=False)
    # This is a terminal snapshot, not a live ContentItem state lookup.  It
    # lets a future consumer distinguish a successful ready item from the
    # normal needs_extension/needs_asr worker outcomes.
    item_state: Mapped[str] = mapped_column(Text, nullable=False)
    error_code: Mapped[str | None] = mapped_column(Text)
    publish_state: Mapped[str] = mapped_column(
        Text, nullable=False, server_default="pending"
    )
    claim_token: Mapped[str | None] = mapped_column(Text)
    claimed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    publish_task_id: Mapped[str | None] = mapped_column(Text)
    enqueued_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        UniqueConstraint(
            "public_id", name="uq_ingest_completion_event_public_id"
        ),
        UniqueConstraint(
            "dispatch_id", name="uq_ingest_completion_event_dispatch"
        ),
        CheckConstraint(
            "outcome IN ('completed', 'failed')",
            name="ck_ingest_completion_event_outcome",
        ),
        CheckConstraint(
            "item_state IN ('ready', 'needs_extension', 'needs_asr', 'failed')",
            name="ck_ingest_completion_event_item_state",
        ),
        CheckConstraint(
            "publish_state IN ('pending', 'claimed', 'enqueued')",
            name="ck_ingest_completion_event_publish_state",
        ),
        CheckConstraint(
            "(outcome = 'completed' AND item_state IN ('ready', 'needs_extension', 'needs_asr') AND error_code IS NULL) OR "
            "(outcome = 'failed' AND item_state = 'failed' AND error_code IS NOT NULL)",
            name="ck_ingest_completion_event_completed_error",
        ),
        Index(
            "ix_ingest_completion_event_publish_claim",
            "publish_state",
            "claimed_at",
        ),
    )


class IngestCompletionDelivery(Base):
    """Claim/ack ledger for one completion-event handler.

    A missing row represents a pending delivery.  Rows are created only when
    a poller claims an event, which keeps the ledger compatible with events
    written by older producers and makes ``(event_id, handler_key)`` the
    durable idempotency key.
    """

    __tablename__ = "ingest_completion_delivery"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    event_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("ingest_completion_event.id", ondelete="CASCADE"),
        nullable=False,
    )
    handler_key: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(
        Text, nullable=False, server_default="claimed"
    )
    disposition: Mapped[str | None] = mapped_column(Text)
    claim_token: Mapped[str | None] = mapped_column(Text)
    claimed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    attempts: Mapped[int] = mapped_column(Integer, nullable=False, server_default="1")
    next_attempt_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    last_error_code: Mapped[str | None] = mapped_column(Text)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        UniqueConstraint(
            "event_id",
            "handler_key",
            name="uq_ingest_completion_delivery_event_handler",
        ),
        CheckConstraint(
            "status IN ('claimed', 'succeeded', 'failed')",
            name="ck_ingest_completion_delivery_status",
        ),
        CheckConstraint(
            "attempts >= 1",
            name="ck_ingest_completion_delivery_attempts",
        ),
        CheckConstraint(
            "last_error_code IS NULL OR last_error_code IN "
            "('outbound_api_key_missing', 'invalid_outbound_target', "
            "'outbound_auth_rejected', 'outbound_contract_invalid', "
            "'outbound_target_not_found', 'outbound_rate_limited', "
            "'outbound_server_error', 'outbound_http_4xx', "
            "'outbound_http_status', 'outbound_timeout', "
            "'outbound_connect_failed', 'outbound_transport_failed', "
            "'redirect_rejected', 'notification_deferred', "
            "'notification_internal_failure', 'retry_exhausted', 'manual_redrive')",
            name="ck_ingest_completion_delivery_error_code",
        ),
        CheckConstraint(
            "(status = 'claimed' AND claim_token IS NOT NULL AND claimed_at IS NOT NULL "
            "AND disposition IS NULL AND last_error_code IS NULL "
            "AND next_attempt_at IS NULL AND completed_at IS NULL) OR "
            "(status = 'succeeded' AND disposition IS NOT NULL AND disposition IN "
            "('sent', 'skipped_no_channel', 'skipped_deleted', "
            "'skipped_identity_disabled', 'skipped_owner_disabled', "
            "'skipped_target_mismatch') "
            "AND completed_at IS NOT NULL AND claim_token IS NULL "
            "AND claimed_at IS NULL AND next_attempt_at IS NULL "
            "AND last_error_code IS NULL) OR "
            "(status = 'failed' AND last_error_code IS NOT NULL "
            "AND claim_token IS NULL AND claimed_at IS NULL "
            "AND completed_at IS NULL AND "
            "((next_attempt_at IS NOT NULL AND disposition IS NULL) OR "
            "(next_attempt_at IS NULL AND disposition IS NOT NULL AND disposition IN "
            "('terminal_failure', 'retry_exhausted'))))",
            name="ck_ingest_completion_delivery_state_contract",
        ),
        Index(
            "ix_ingest_completion_delivery_claim",
            "status",
            "next_attempt_at",
            "claimed_at",
        ),
        Index(
            "ix_ingest_completion_delivery_event",
            "event_id",
        ),
    )


class Segment(Base):
    __tablename__ = "segment"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    item_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("content_item.id", ondelete="CASCADE"), nullable=False
    )
    seq: Mapped[int] = mapped_column(Integer, nullable=False)

    # 定位符：视频用秒，图文用字符偏移；互斥（见 loc_ck）
    start_sec: Mapped[float | None] = mapped_column(Numeric(9, 2))
    end_sec: Mapped[float | None] = mapped_column(Numeric(9, 2))
    char_start: Mapped[int | None] = mapped_column(Integer)
    char_end: Mapped[int | None] = mapped_column(Integer)
    anchor: Mapped[str | None] = mapped_column(Text)  # 图文：段落序号或标题锚点

    text: Mapped[str] = mapped_column(Text, nullable=False)
    embedding: Mapped[list[float] | None] = mapped_column(Vector(1536))
    fts: Mapped[str | None] = mapped_column(TSVECTOR)
    boundary_kind: Mapped[str] = mapped_column(
        Text, nullable=False
    )  # chapter|gap|punct|semantic|hard_cut

    __table_args__ = (
        CheckConstraint(
            "(start_sec IS NOT NULL AND char_start IS NULL) OR "
            "(char_start IS NOT NULL AND start_sec IS NULL)",
            name="loc_ck",
        ),
        UniqueConstraint("item_id", "seq", name="uq_segment_item_id_seq"),
        Index("ix_segment_fts_gin", "fts", postgresql_using="gin"),
        Index(
            "ix_segment_text_trgm_gin",
            "text",
            postgresql_using="gin",
            postgresql_ops={"text": "gin_trgm_ops"},
        ),
    )
